### ISSUE TITLE
GithubException when doing complex transformations

### ISSUE THREAD

**Issue by KarstenSiemer** [argoproj-labs/gordian#28]
Hi Guys!
First of all thank you for your work on this project!

I already successfully created some PRs using the simple search and replace syntax. Forking and all that stuff working great.

Now I want to do complex transformations but fail.

This is my transformation script:
```
import sys
import time
from github import GithubException
from gordian.gordian import get_basic_parser, apply_transformations
from gordian.transformations import Transformation
from gordian.config import Config
from gordian.repo import Repo

class PreScale(Transformation):

    def __init__(self, args, repo):
        super().__init__(args, repo)
        self.environments = args.environments
        self.image = args.image
        self.image_tag = args.image_tag

    def run(self):
        for env in self.environments:
            objects = self.repo.get_objects(f'kustomizations/overlays/{env}/kustomization.yaml')

            for obj in objects:
                if obj['kind'] != 'Kustomization':
                    continue

                for img in obj['images']:
                    if img['name'] != self.image:
                        continue

                    img['newTag'] = self.image_tag

                for i in range (1, 4):
                    try:
                        objects.save(f'Setting {self.image} image tag to {self.image_tag}', self.dry_run)
                    except GithubException as e:
                        time.sleep(i)

if __name__ == '__main__':
    parser = get_basic_parser()
    parser.add_argument(
        '-e', '--environments',
        required=True,
        dest='environments',
        action='append',
        help='Environments to update.'
    )
    parser.add_argument(
        '-i', '--image',
        required=True,
        dest='image',
        action='store',
        help='image to update.'
    )
    parser.add_argument(
        '-a', '--image-tag',
        required=True,
        dest='image_tag',
        action='store',
        help='tag for the image to update.'
    )
    args = parser.parse_args(sys.argv[1:])
    apply_transformations(args, [PreScale])

```
I added the for loop with the sleeps because I was getting this error:
```
16:52:12  + python -u gordian/transformation.py --config gordian/destinationRepositories.yaml --github-api https://api.github.com --pr Update-sda-bash-utils-to-0.2.0-dev-202006290251 --branch sda-bash-utils-0.2.0-dev-202006290251 --target-branch dev --image quay.io/sdase/sda-bash-utils --image-tag 0.2.0-dev-202006290251 --environments dev --patch --verbose
16:52:12  [2020-06-29 14:52:12,397] gordian.transform INFO Processing repo: some-repo
16:52:12  [2020-06-29 14:52:12,397] repo.__init__ DEBUG Using git username and password
16:52:12  [2020-06-29 14:52:12,656] repo.__init__ DEBUG Github api url: https://api.github.com
16:52:12  [2020-06-29 14:52:12,656] repo.__init__ DEBUG Repo name: some-repo
16:52:12  [2020-06-29 14:52:12,656] repo.__init__ DEBUG Target ref: dev
16:52:12  [2020-06-29 14:52:12,656] repo.__init__ DEBUG Branch name for this changes: refs/heads/sda-bash-utils-0.2.0-dev-202006290251
16:52:12  [2020-06-29 14:52:12,656] repo.get_files DEBUG Getting repo content
16:52:25  [2020-06-29 14:52:24,823] repo._get_new_version INFO There is no version file in the repository, skipping bumping
16:52:25  [2020-06-29 14:52:25,020] repo.update_file INFO Setting quay.io/sdase/sda-bash-utils image tag to 0.2.0-dev-202006290251
16:52:25  [2020-06-29 14:52:25,020] repo._make_branch INFO Forking repo...
16:52:25  [2020-06-29 14:52:25,420] repo._get_branch DEBUG Fetching branch dev...
16:52:25  [2020-06-29 14:52:25,651] repo._make_branch DEBUG Creating branch refs/heads/sda-bash-utils-0.2.0-dev-202006290251
16:52:26  [2020-06-29 14:52:26,466] repo.update_file DEBUG Updating file kustomizations/overlays/dev/kustomization.yaml
16:52:26  Traceback (most recent call last):
16:52:26    File "gordian/transformation.py", line 32, in run
16:52:26      objects.save(f'Setting {self.image} image tag to {self.image_tag}', self.dry_run)
16:52:26    File "/usr/local/lib/python3.7/site-packages/gordian/files/base_file.py", line 26, in save
16:52:26      self.repo.update_file(self.github_file, self._dump(), message, dry_run)
16:52:26    File "/usr/local/lib/python3.7/site-packages/gordian/repo.py", line 158, in update_file
16:52:26      branch=self.branch_name
16:52:26    File "/usr/local/lib/python3.7/site-packages/github/Repository.py", line 2101, in update_file
16:52:26      input=put_parameters,
16:52:26    File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
16:52:26      verb, url, parameters, headers, input, self.__customConnection(url)
16:52:26    File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 342, in __check
16:52:26      raise self.__createException(status, responseHeaders, output)
16:52:26  github.GithubException.GithubException: 409 {"message": "kustomizations/overlays/dev/kustomization.yaml does not match 2741f1836ecb27558f61bd1e9246005cc415c7a2", "documentation_url": "https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
```

Because I thought it was doing the commit too fast after the fork.
Like discussed here: https://stackoverflow.com/questions/33666838/determine-if-a-fork-is-ready

With the for loop it still fails like this:
```
09:12:51  + python -u gordian/transformation.py --config gordian/destinationRepositories.yaml --github-api https://api.github.com --pr Update-sda-bash-utils-to-0.1.4-dev-202006300712 --branch sda-bash-utils-0.1.4-dev-202006300712 --target-branch dev --image quay.io/sdase/sda-bash-utils --image-tag 0.1.4-dev-202006300712 --environments dev --patch --verbose
09:12:51  [2020-06-30 07:12:51,854] gordian.transform INFO Processing repo: some-repo
09:12:51  [2020-06-30 07:12:51,855] repo.__init__ DEBUG Using git username and password
09:12:52  [2020-06-30 07:12:52,110] repo.__init__ DEBUG Github api url: https://api.github.com
09:12:52  [2020-06-30 07:12:52,110] repo.__init__ DEBUG Repo name: some-repo
09:12:52  [2020-06-30 07:12:52,110] repo.__init__ DEBUG Target ref: dev
09:12:52  [2020-06-30 07:12:52,110] repo.__init__ DEBUG Branch name for this changes: refs/heads/sda-bash-utils-0.1.4-dev-202006300712
09:12:52  [2020-06-30 07:12:52,110] repo.get_files DEBUG Getting repo content
09:13:07  [2020-06-30 07:13:05,321] repo._get_new_version INFO There is no version file in the repository, skipping bumping
09:13:07  [2020-06-30 07:13:05,660] repo.update_file INFO Setting quay.io/sdase/sda-bash-utils image tag to 0.1.4-dev-202006300712
09:13:07  [2020-06-30 07:13:05,661] repo._make_branch INFO Forking repo...
09:13:07  [2020-06-30 07:13:05,982] repo._get_branch DEBUG Fetching branch dev...
09:13:07  [2020-06-30 07:13:06,215] repo._make_branch DEBUG Creating branch refs/heads/sda-bash-utils-0.1.4-dev-202006300712
09:13:07  [2020-06-30 07:13:06,937] repo.update_file DEBUG Updating file kustomizations/overlays/dev/kustomization.yaml
09:13:08  [2020-06-30 07:13:08,183] repo.update_file INFO Setting quay.io/sdase/sda-bash-utils image tag to 0.1.4-dev-202006300712
09:13:08  [2020-06-30 07:13:08,183] repo.update_file DEBUG Updating file kustomizations/overlays/dev/kustomization.yaml
09:13:10  [2020-06-30 07:13:10,418] repo.update_file INFO Setting quay.io/sdase/sda-bash-utils image tag to 0.1.4-dev-202006300712
09:13:10  [2020-06-30 07:13:10,418] repo.update_file DEBUG Updating file kustomizations/overlays/dev/kustomization.yaml
09:13:14  [2020-06-30 07:13:14,048] gordian.transform INFO PR already exists for refs/heads/sda-bash-utils-0.1.4-dev-202006300712. Error: 422 {"message": "Validation Failed", "errors": [{"resource": "PullRequest", "code": "custom", "message": "No commits between SDA-SE:dev and ****:sda-bash-utils-0.1.4-dev-202006300712"}], "documentation_url": "https://developer.github.com/v3/pulls/#create-a-pull-request"}
```
Even though it says that a PR already exists, there was none created.
Guessing that the commit itself internally worked at first try and my loop is incorrect, because only the push fails and it tries to issue a commit again, which cannot have any differences.
Not sure how to solve it.

The file I am trying to transform looks like this
kustomizations/overlays/dev/kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

configurations:
  - configurations.yaml

images:
- name: quay.io/sdase/sda-bash-utils
  newTag: "0.2.0-202006250718"
- name: someimage
  newTag: "sometag"
```

When I add print commands to the transformation script I can clearly see that the function itself is properly swapping the tags.

Version of gordian used is 2.1.2

**Comment by jnevelson** [comment]
Thanks for the feedback and opening the issue with such good instructions! I'm able to reproduce the issue, and we're thinking about what the best solution is.

The issue is the `--branch` argument that is being passed in. The way Gordian works is that it waits to fork the repo until it's ready to save a file. This is so that it doesn't unnecessarily fork a repo if it's being operated as a dry-run. That means that it always reads the file contents from the original repo, _even if a fork already exists_. If this your own repo, calling `create_fork()` is a no-op, but internally it still maintains a separate reference between the forked repo and the original repo.

I'm looking at creating a solution that allows both variations - create a new fork and create a randomly-generated branch name, or read from a branch that already exists. The main problem will be communicating to the end user that those are incompatible with each other, meaning that if a fork does not exist, you will not be able to pass `--branch` in, as that branch does not yet exist. Maybe part of the solution is to rename/specify that the `--branch` argument also means "this is the branch Gordian reads the file contents from".

**Comment by jnevelson** [comment]
Are you using Gordian to add commits to a branch that already exists? If not, I'd recommend avoiding the `--branch` flag for now, at least until we come up with a fix for this bug. The branch name will default to a timestamp.

**Comment by jnevelson** [comment]
@KarstenSiemer what do you think about this as a possible solution?

We made a change last week (in 2.x.x) to always fork the repo to get around issues with write permissions. With your bug report, we're realizing that there are a lot of edge cases that get created when a repo is forked and `--branch` is specified. 

What do you think about us adding a `--fork` flag to make forking the repo optional. For now, we're thinking to get around the complexity of dealing with a named branch by making `--branch` mutually exclusive with `--fork` - meaning that if you wish to specify a branch name, you cannot fork the repo (you need write permissions on the repo you're specifying). If `--fork` is passed in, a repo fork will be created even if it's a dry-run.

**Comment by KarstenSiemer** [comment]
Hello @jnevelson,
thanks for this precise answer and your dedication on resolving this issue.

I really like the concept of forking the repo. This gives me the possibility of using a bot user that only has read privileges and all repos except his own forks. And I think this should be the default way of doing this.
I was using the '--branch' option because I started testing before 2.x.x. 

When moving to this newer version my first thought was why a fork isn't optional but after using it, I totally got it.
Making it mutually exclusive and forking optional would maybe be the best approach to attract new users though. Most might come with the incentive to just create a new branch and make a pr because it's closest to how they are working themselves on self owned repositories and might feel like forking is an overhead.


A bit more information on my setup.
The target branch, in this case dev, is already existing.
I am using a bot user, that right now still does have read/write on the target repository.

Not specifying the '--branch' option isn't solving the issue for me.
```
08:32:12  + python -u gordian/transformation.py --config gordian/destinationRepositories.yaml --github-api https://api.github.com --pr Update-sda-bash-utils-to-0.1.4-dev-202007010631 --target-branch dev --image quay.io/sdase/sda-bash-utils --image-tag 0.1.4-dev-202007010631 --environments dev --patch --verbose
08:32:12  [2020-07-01 06:32:12,072] gordian.transform INFO Processing repo: some-repo
08:32:12  [2020-07-01 06:32:12,073] repo.__init__ DEBUG Using git username and password
08:32:12  [2020-07-01 06:32:12,348] repo.__init__ DEBUG Github api url: https://api.github.com
08:32:12  [2020-07-01 06:32:12,348] repo.__init__ DEBUG Repo name: some-repo
08:32:12  [2020-07-01 06:32:12,348] repo.__init__ DEBUG Target ref: dev
08:32:12  [2020-07-01 06:32:12,348] repo.__init__ DEBUG Branch name for this changes: refs/heads/2020-07-01-063212.348307
08:32:12  [2020-07-01 06:32:12,348] repo.get_files DEBUG Getting repo content
08:32:24  [2020-07-01 06:32:24,203] repo._get_new_version INFO There is no version file in the repository, skipping bumping
08:32:24  [2020-07-01 06:32:24,415] repo.update_file INFO Setting quay.io/sdase/sda-bash-utils image tag to 0.1.4-dev-202007010631
08:32:24  [2020-07-01 06:32:24,415] repo._make_branch INFO Forking repo...
08:32:25  [2020-07-01 06:32:24,815] repo._get_branch DEBUG Fetching branch dev...
08:32:25  [2020-07-01 06:32:25,095] repo._make_branch DEBUG Creating branch refs/heads/2020-07-01-063212.348307
08:32:25  [2020-07-01 06:32:25,855] repo.update_file DEBUG Updating file kustomizations/overlays/dev/kustomization.yaml
08:32:26  Traceback (most recent call last):
08:32:26    File "gordian/transformation.py", line 57, in <module>
08:32:26      apply_transformations(args, [PreScale])
08:32:26    File "/usr/local/lib/python3.7/site-packages/gordian/gordian.py", line 158, in apply_transformations
08:32:26      transform(args, transformations, config.get_data(), pr_description, pr_created_callback=pr_created_callback)
08:32:26    File "/usr/local/lib/python3.7/site-packages/gordian/gordian.py", line 172, in transform
08:32:26      transformation(args, repo).run()
08:32:26    File "gordian/transformation.py", line 31, in run
08:32:26      objects.save(f'Setting {self.image} image tag to {self.image_tag}', self.dry_run)
08:32:26    File "/usr/local/lib/python3.7/site-packages/gordian/files/base_file.py", line 26, in save
08:32:26      self.repo.update_file(self.github_file, self._dump(), message, dry_run)
08:32:26    File "/usr/local/lib/python3.7/site-packages/gordian/repo.py", line 158, in update_file
08:32:26      branch=self.branch_name
08:32:26    File "/usr/local/lib/python3.7/site-packages/github/Repository.py", line 2101, in update_file
08:32:26      input=put_parameters,
08:32:26    File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
08:32:26      verb, url, parameters, headers, input, self.__customConnection(url)
08:32:26    File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 342, in __check
08:32:26      raise self.__createException(status, responseHeaders, output)
08:32:26  github.GithubException.GithubException: 409 {"message": "kustomizations/overlays/dev/kustomization.yaml does not match 2741f1836ecb27558f61bd1e9246005cc415c7a2", "documentation_url": "https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
``` 

Using a simple search and replace operation works however fine even with '--branch' specified:
```
09:03:18  + gordian --config gordian/destinationRepositories.yaml --github-api https://api.github.com --pr Update-sda-bash-utils-to-0.1.4-dev-202007010702 --branch sda-bash-utils-0.1.4-dev-202007010702 --target-branch dev --search 0.1.1-202006120921 --replace 0.1.4-dev-202007010702 --patch --verbose
09:03:19  [2020-07-01 07:03:18,793] gordian.transform INFO Processing repo: some-repo
09:03:19  [2020-07-01 07:03:18,793] repo.__init__ DEBUG Using git username and password
09:03:19  [2020-07-01 07:03:19,077] repo.__init__ DEBUG Github api url: https://api.github.com
09:03:19  [2020-07-01 07:03:19,077] repo.__init__ DEBUG Repo name: some-repo
09:03:19  [2020-07-01 07:03:19,077] repo.__init__ DEBUG Target ref: dev
09:03:19  [2020-07-01 07:03:19,077] repo.__init__ DEBUG Branch name for this changes: refs/heads/sda-bash-utils-0.1.4-dev-202007010702
09:03:19  [2020-07-01 07:03:19,077] repo.get_files DEBUG Getting repo content
09:03:34  [2020-07-01 07:03:32,418] repo._get_new_version INFO There is no version file in the repository, skipping bumping
09:03:34  [2020-07-01 07:03:32,875] transformations.run DEBUG Ignoring ContentFile(path=".gitignore")
09:03:34  [2020-07-01 07:03:33,075] repo.update_file INFO Replacing '0.1.1-202006120921' with '0.1.4-dev-202007010702' in ContentFile(path="Jenkinsfile-cleanup.next")
09:03:34  [2020-07-01 07:03:33,075] repo._make_branch INFO Forking repo...
09:03:34  [2020-07-01 07:03:33,490] repo._get_branch DEBUG Fetching branch dev...
09:03:34  [2020-07-01 07:03:33,712] repo._make_branch DEBUG Creating branch refs/heads/sda-bash-utils-0.1.4-dev-202007010702
09:03:34  [2020-07-01 07:03:34,470] repo.update_file DEBUG Updating file Jenkinsfile-cleanup.next
09:03:36  [2020-07-01 07:03:35,735] repo.update_file INFO Replacing '0.1.1-202006120921' with '0.1.4-dev-202007010702' in ContentFile(path="Jenkinsfile.next")
09:03:36  [2020-07-01 07:03:35,735] repo.update_file DEBUG Updating file Jenkinsfile.next
09:04:23  [2020-07-01 07:04:22,544] gordian.transform INFO PR created: Update-sda-bash-utils-to-0.1.4-dev-202007010702. Branch: refs/heads/sda-bash-utils-0.1.4-dev-202007010702. Labels: []
09:04:23  [2020-07-01 07:04:22,544] gordian.transform INFO Pull requests
09:04:23  [2020-07-01 07:04:22,544] gordian.<listcomp> INFO https://github.com/some-repo/pull/109
```

**Comment by KarstenSiemer** [comment]
I moved back to v1.4.1 where complex transformations still work for me.
Giving it a second thought, I positively think the best solution would indeed be to make forking optional and --branch mutually exclusive.

**Comment by jnevelson** [comment]
@KarstenSiemer thanks for the added detail - I'll look into this some more.

As a general strategy though, I think we'll move forward with `--fork` and `--branch` being mutually exclusive to keep things simple. Agreed that forking should have been optional to begin with. We were trying to keep it simple, but that clearly wasn't how it worked out 😑

Look out for another update in the next week or so!

**Comment by jnevelson** [comment]
@KarstenSiemer `argoprojlabs/gordian:v3.0.0` is now available from Dockerhub. As mentioned above, `--fork` is now an optional parameter (by default it will create a branch in the specified repo as per the "old" behavior) and it will _not_ allow passing in `--branch` when forking because of the edge cases you discovered.

Please give it a try when you get a chance to; hopefully this fixes the issues 🤞

**Comment by KarstenSiemer** [comment]
sorry for my unresponsiveness. Haven't have time yet to check and wont have for the next two weeks, i guess.
I am currently still using the old version and will update you guys when I update.
Thanks for your work, I'll close this for now 👍
