### ISSUE TITLE
Process is failing if branch is provided

### ISSUE THREAD

**Issue by estahn** [argoproj-labs/gordian#33]
I'm running the following command:

```bash
python3 chart-updater.py -c gordian.yaml -b argocd-chart-update --pr update_chart_version 
```

I'm getting the following error message:

```
[2020-10-28 19:43:28,353] INFO Processing repo: hipagesgroup/salesforce-syncer
Traceback (most recent call last):
  File "chart-updater.py", line 84, in <module>
    main()
  File "chart-updater.py", line 81, in main
    apply_transformations(args, [ChartUpdater])
  File "/usr/local/lib/python3.8/site-packages/gordian/gordian.py", line 167, in apply_transformations
    transform(args, transformations, config.get_data(), pr_description, pr_created_callback=pr_created_callback)
  File "/usr/local/lib/python3.8/site-packages/gordian/gordian.py", line 188, in transform
    transformation(args, repo).run()
  File "chart-updater.py", line 20, in run
    file = self.repo.find_file(f'.argocd.yml')
  File "/usr/local/lib/python3.8/site-packages/gordian/repo.py", line 92, in find_file
    for file in self.get_files():
  File "/usr/local/lib/python3.8/site-packages/gordian/repo.py", line 74, in get_files
    contents = self._get_repo_contents('')
  File "<decorator-gen-2>", line 2, in _get_repo_contents
  File "/usr/local/lib/python3.8/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/usr/local/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/lib/python3.8/site-packages/gordian/repo.py", line 128, in _get_repo_contents
    raise e
  File "/usr/local/lib/python3.8/site-packages/gordian/repo.py", line 125, in _get_repo_contents
    return self._source_repo.get_contents(path, self.source_branch)
  File "/usr/local/lib/python3.8/site-packages/github/Repository.py", line 1752, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 404 {"message": "No commit found for the ref refs/heads/argocd-chart-update", "documentation_url": "https://docs.github.com/v3/repos/contents/"}
```

**Comment by AgarFu** [comment]
Hey @estahn thank you for reaching out, what is your expectation when you pass the branch to your script?

**Comment by estahn** [comment]
@AgarFu I would expect it to read from the target branch (master) until a new branch exists. I made a workaround that seems to work:

```pyton
class ChartUpdater(Transformation):
    def run(self):
        # Workaround to fix if -b is provided.
        try:
            self.repo._target_repo.get_branch(self.repo.source_branch)
        except:
            self.repo.source_branch = self.repo.target_ref

        files = ['.argocd.yml', '.argocd.branches.yml']
        for f in files:
            logger.info(f"Processing file: {f}")

            file = self.repo.get_objects(f)

            ...
```
